version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application

permissions:
  - object: /home/ec2-user/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 775
    type:
     - file
hooks:
  BeforeInstall:
    - location: shutdown.sh
      timeout: 180 
    - location: remove.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: startup.sh
      timeout: 180
      runas: root
